
spring:
  datasource:
    name: mysite
    type: com.alibaba.druid.pool.DruidDataSource
      #druid相关配置
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://101.37.27.120:3306/mysite?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      #配置初始化大小/最小/最大
      initial-size: 10
      min-idle: 10
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false

      #监控统计拦截的filters
      filters: stat,wall,slf4j
      max-pool-prepared-statement-per-connection-size: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bubudeai.entity

server:
  port: 8080
